# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compression.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compression.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63ompression.proto\"\r\n\x0bJoinRequest\"\x0b\n\tJoinReply\"P\n\x12\x43ompressionRequest\x12\x12\n\ninput_file\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\x12\x11\n\tbyte_size\x18\x03 \x01(\r\"\x12\n\x10\x43ompressionReply\"?\n\x14\x44\x65\x63ompressionRequest\x12\x12\n\ninput_file\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\"\x14\n\x12\x44\x65\x63ompressionReply\"_\n\x08Metadata\x12\x11\n\tbyte_size\x18\x01 \x01(\t\x12\x17\n\x07indices\x18\x02 \x03(\x0b\x32\x06.Index\x12\x14\n\x0ctotal_frames\x18\x03 \x01(\x04\x12\x11\n\tfile_path\x18\x04 \x01(\t\"K\n\x05Index\x12\x14\n\x0c\x61\x62s_position\x18\x01 \x01(\x04\x12\x14\n\x0crel_position\x18\x02 \x01(\x04\x12\x16\n\x0e\x63ontainer_file\x18\x03 \x01(\t2f\n\nCompressor\x12\x34\n\x08\x43ompress\x12\x13.CompressionRequest\x1a\x11.CompressionReply\"\x00\x12\"\n\x04Join\x12\x0c.JoinRequest\x1a\n.JoinReply\"\x00\x32n\n\x0c\x44\x65\x63ompressor\x12:\n\nDecompress\x12\x15.DecompressionRequest\x1a\x13.DecompressionReply\"\x00\x12\"\n\x04Join\x12\x0c.JoinRequest\x1a\n.JoinReply\"\x00\x62\x06proto3'
)




_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=34,
)


_JOINREPLY = _descriptor.Descriptor(
  name='JoinReply',
  full_name='JoinReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=47,
)


_COMPRESSIONREQUEST = _descriptor.Descriptor(
  name='CompressionRequest',
  full_name='CompressionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_file', full_name='CompressionRequest.input_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_file', full_name='CompressionRequest.output_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='byte_size', full_name='CompressionRequest.byte_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=129,
)


_COMPRESSIONREPLY = _descriptor.Descriptor(
  name='CompressionReply',
  full_name='CompressionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=149,
)


_DECOMPRESSIONREQUEST = _descriptor.Descriptor(
  name='DecompressionRequest',
  full_name='DecompressionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_file', full_name='DecompressionRequest.input_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_file', full_name='DecompressionRequest.output_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=214,
)


_DECOMPRESSIONREPLY = _descriptor.Descriptor(
  name='DecompressionReply',
  full_name='DecompressionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=236,
)


_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='byte_size', full_name='Metadata.byte_size', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indices', full_name='Metadata.indices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_frames', full_name='Metadata.total_frames', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='Metadata.file_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=333,
)


_INDEX = _descriptor.Descriptor(
  name='Index',
  full_name='Index',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='abs_position', full_name='Index.abs_position', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rel_position', full_name='Index.rel_position', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='container_file', full_name='Index.container_file', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=410,
)

_METADATA.fields_by_name['indices'].message_type = _INDEX
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinReply'] = _JOINREPLY
DESCRIPTOR.message_types_by_name['CompressionRequest'] = _COMPRESSIONREQUEST
DESCRIPTOR.message_types_by_name['CompressionReply'] = _COMPRESSIONREPLY
DESCRIPTOR.message_types_by_name['DecompressionRequest'] = _DECOMPRESSIONREQUEST
DESCRIPTOR.message_types_by_name['DecompressionReply'] = _DECOMPRESSIONREPLY
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['Index'] = _INDEX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUEST,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:JoinRequest)
  })
_sym_db.RegisterMessage(JoinRequest)

JoinReply = _reflection.GeneratedProtocolMessageType('JoinReply', (_message.Message,), {
  'DESCRIPTOR' : _JOINREPLY,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:JoinReply)
  })
_sym_db.RegisterMessage(JoinReply)

CompressionRequest = _reflection.GeneratedProtocolMessageType('CompressionRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPRESSIONREQUEST,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:CompressionRequest)
  })
_sym_db.RegisterMessage(CompressionRequest)

CompressionReply = _reflection.GeneratedProtocolMessageType('CompressionReply', (_message.Message,), {
  'DESCRIPTOR' : _COMPRESSIONREPLY,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:CompressionReply)
  })
_sym_db.RegisterMessage(CompressionReply)

DecompressionRequest = _reflection.GeneratedProtocolMessageType('DecompressionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DECOMPRESSIONREQUEST,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:DecompressionRequest)
  })
_sym_db.RegisterMessage(DecompressionRequest)

DecompressionReply = _reflection.GeneratedProtocolMessageType('DecompressionReply', (_message.Message,), {
  'DESCRIPTOR' : _DECOMPRESSIONREPLY,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:DecompressionReply)
  })
_sym_db.RegisterMessage(DecompressionReply)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:Metadata)
  })
_sym_db.RegisterMessage(Metadata)

Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), {
  'DESCRIPTOR' : _INDEX,
  '__module__' : 'compression_pb2'
  # @@protoc_insertion_point(class_scope:Index)
  })
_sym_db.RegisterMessage(Index)



_COMPRESSOR = _descriptor.ServiceDescriptor(
  name='Compressor',
  full_name='Compressor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=412,
  serialized_end=514,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compress',
    full_name='Compressor.Compress',
    index=0,
    containing_service=None,
    input_type=_COMPRESSIONREQUEST,
    output_type=_COMPRESSIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Join',
    full_name='Compressor.Join',
    index=1,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPRESSOR)

DESCRIPTOR.services_by_name['Compressor'] = _COMPRESSOR


_DECOMPRESSOR = _descriptor.ServiceDescriptor(
  name='Decompressor',
  full_name='Decompressor',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=516,
  serialized_end=626,
  methods=[
  _descriptor.MethodDescriptor(
    name='Decompress',
    full_name='Decompressor.Decompress',
    index=0,
    containing_service=None,
    input_type=_DECOMPRESSIONREQUEST,
    output_type=_DECOMPRESSIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Join',
    full_name='Decompressor.Join',
    index=1,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DECOMPRESSOR)

DESCRIPTOR.services_by_name['Decompressor'] = _DECOMPRESSOR

# @@protoc_insertion_point(module_scope)
